services:
  postgres-db:
    image: postgres
    container_name: postgres-e-learning-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=e-learning-platform
    ports:
      - '5432:5432'
